[package]
name = "rsmonkey"
version = "0.1.0"
authors = ["Max Mindlin <maxmindlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
	"rsmonkey-parser",
	"rsmonkey-repl"
]

[dependencies]
