[package]
name = "rsmonkey-repl"
version = "0.1.0"
authors = ["Max Mindlin <maxmindlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsmonkey-parser = { path = "../rsmonkey-parser" }
rustyline = "8.0.0"
